### ISSUE TITLE
[ERROR] usb3380_context_init_ex Unable to open USB3380

### ISSUE THREAD

**Issue by ducnguyenAstro** [xtrx-sdr/libusb3380#2]
When running ./test_libusb3380 -t -l2
with XTRX attached on the USB3 box and USB3 port is connected.
lsusb did see the chip as:
Bus 002 Device 002: ID 0525:3380 Netchip Technology, Inc

and dmesg command:
dmesg | grep usb
[  251.537517] usb 2-3: new SuperSpeed USB device number 2 using xhci_hcd
[  251.557852] usb 2-3: New USB device found, idVendor=0525, idProduct=3380
[  251.557860] usb 2-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  251.557866] usb 2-3: Product: USB3 + 1 PCIe + RC mode - 88-pin single-row QFN
[  251.557872] usb 2-3: Manufacturer: PLX Technology, Inc.

**Comment by sergforce** [comment]
test_libusb3380 is a basic test utility to check whether USB3380 wrapper is working. It's not doing any XTRX related things.
Probably you meant `./test_xtrx -t -l2` ?

**Comment by smallkid** [comment]
hi i have issue when testing the libusb3880
when running  sudo ./test_libusb3380 
[ERROR] usb3380_int_csr_cfg_read Unable to usb3380_int_csrin_sync!
this error also show on log when running osmo-trx
kindly advice

**Comment by sergforce** [comment]
Can you run `./test_xtrx -t -l9` to see what's happening?

**Comment by smallkid** [comment]
i tried this is the output
sudo ./test_xtrx -t -l9
Segmentation fault (core dumped)
btw i use ubuntu 16,04LTS i686 and port is USB 2.0

**Comment by smallkid** [comment]
this is the output when i run osmo-trx-xtx
sudo ./build/Transceiver52M/osmo-trx-xtrx -C osmo-trx.cfg 
Sat Jan 26 21:57:09 2019 DLGLOBAL <0003> telnet_interface.c:104 Available via telnet 127.0.0.1 4237
Sat Jan 26 21:57:09 2019 DLCTRL <000a> control_if.c:911 CTRL at 127.0.0.1 4236
Config Settings
   Log Level............... 0
   Device args............. 
   TRX Base Port........... 5700
   TRX Address............. 127.0.0.1
   GSM BTS Address......... 127.0.0.1
   Channels................ 1
   Tx Samples-per-Symbol... 4
   Rx Samples-per-Symbol... 4
   EDGE support............ 0
   Reference............... 0
   C0 Filler Table......... 1
   Multi-Carrier........... 0
   Tuning offset........... 0
   RSSI to dBm offset...... 0
   Swap channels........... 0
   Tx Antennas............. 'BAND1'
   Rx Antennas............. 'LNAW'

Setting SCHED_RR priority(18)
Sat Jan 26 21:57:09 2019 DMAIN <0000> XTRXDevice.cpp:44 [tid=3075066176] creating XTRX device: RXSPS: 4 TXSPS: 4 chans: 1 lo_off: 0 rx_path(0): LNAW tx_path(0): BAND1
Sat Jan 26 21:57:09 2019 DMAIN <0000> XTRXDevice.cpp:81 [tid=3075066176] opening XTRX device ''..
Segmentation fault (core dumped)

**Comment by sergforce** [comment]
Unfortunately, I wasn't able to repeat Segmentation fault.

Can you run under debugger so I can get insight where it fails
```
gdb --args ./test_xtrx -t -l9
...
(gdb) r
```

**Comment by smallkid** [comment]
smallkid@darkstar03X-PC:~/sdr/xtrx-sdr/images_2019/sources/build/libxtrx$ gdb --args ./test_xtrx -t -l9
......
Reading symbols from ./test_xtrx...done.
(gdb) r
Starting program: /home/smallkid/sdr/xtrx-sdr/images_2019/sources/build/libxtrx/test_xtrx -t -l9
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7ab7700 (LWP 29481)]

Thread 1 "test_xtrx" received signal SIGSEGV, Segmentation fault.
__GI__IO_fputs (
    str=0x7fffffffa700 "20:46:56.122402 DEBUG:  find_usb_match:416 [USB3] usb3380: comparing devices -1/-1/-1 <> 2/2/8\n", fp=0x0) at iofputs.c:36
36	iofputs.c: No such file or directory.
(gdb)

**Comment by smallkid** [comment]
same issue when i run in osmo-trx (xtrx build)

(gdb) r
Starting program: /home/smallkid/sdr/xtrx-sdr/osmo-trx/build/Transceiver52M/osmo-trx-xtrx -C ../../doc/examples/osmo-trx-xtrx/osmo-trx-xtrx.cfg
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Thu Jan 31 20:49:22 2019 DLGLOBAL <0003> telnet_interface.c:104 Available via telnet 127.0.0.1 4237
Thu Jan 31 20:49:22 2019 DLCTRL <000a> control_if.c:911 CTRL at 127.0.0.1 4236
Config Settings
   Log Level............... 0
   Device args............. 
   TRX Base Port........... 5700
   TRX Address............. 127.0.0.1
   GSM BTS Address......... 127.0.0.1
   Channels................ 1
   Tx Samples-per-Symbol... 4
   Rx Samples-per-Symbol... 4
   EDGE support............ 0
   Reference............... 0
   C0 Filler Table......... 1
   Multi-Carrier........... 0
   Tuning offset........... 0
   RSSI to dBm offset...... 0
   Swap channels........... 0
   Tx Antennas............. 'BAND1'
   Rx Antennas............. 'LNAW'

Setting SCHED_RR priority(18)
Thu Jan 31 20:49:22 2019 DMAIN <0000> XTRXDevice.cpp:44 [tid=140737326017472] creating XTRX device: RXSPS: 4 TXSPS: 4 chans: 1 lo_off: 0 rx_path(0): LNAW tx_path(0): BAND1
Thu Jan 31 20:49:22 2019 DMAIN <0000> XTRXDevice.cpp:81 [tid=140737326017472] opening XTRX device ''..
[New Thread 0x7ffff652b700 (LWP 29667)]

Thread 1 "osmo-trx-xtrx" received signal SIGSEGV, Segmentation fault.
__GI__IO_fputs (str=0x7fffffffd3e0 "20:49:22.929127 INFO:   [USB3] USB3380 dual fly GPEP RX mode is on, TX mode is on\n", fp=0x0) at iofputs.c:36
36	iofputs.c: No such file or directory.
(gdb)

**Comment by sergforce** [comment]
thank you. Can you run `bt`. Just for `./test_xtrx`, no need to retest in `osmo-trx-xtrx` now

**Comment by smallkid** [comment]
where can i find bt command ? its bad command on ubuntu18.04

it works if no args also on loglevel 1
smallkid@darkstar03X-PC:
~/sdr/xtrx-sdr/images/sources/build/libxtrx$ ./test_xtrx 
Usage: DMATX and/or DMARX must be enabled (or TX REPEAT is set)!
[00] usb3380://2/2/9                  2.2:9            USB              5Gbit           
smallkid@darkstar03X-PC:~/sdr/xtrx-sdr/images/sources/build/libxtrx$ ./test_xtrx -t -l1
CPU Features: SSE2+ SSE4.1+ AVX+ FMA+
Master: 32.000 MHz; RX rate: 4.000 MHz; TX rate: 0.000 MHz
RX tunned: 900000000.000000
RX bandwidth: 2000000.000000
RX LNA gain: 15.000000
RX PGA gain: 0.000000
RX TIA gain: 9.000000
RX CYCLES=1 SAMPLES=16384 SLICE=16384 (PARTS=1)
PROCESSED RX SLICE 0 /0: res 0 TS:    8192       4077 us DELTA      5 us LATE   2034 us 16384 samples
RX STAT Overruns:0
Success!
Processed 1 devs, each: RX 2 x 10.022 = 20.045 MSPS (WIRE: 80.178915)    TX 2 x 0.000 = 0.000 MSPS (WIRE: 0.000000 MB/s) 
smallkid@darkstar03X-PC:~/sdr/xtrx-sdr/images/sources/build/libxtrx$ ./test_xtrx -t -l2
Segmentation fault (core dumped)
smallkid@darkstar03X-PC:~/sdr/xtrx-sdr/images/sources/build/libxtrx$

**Comment by sergforce** [comment]
I mean backtrace `bt` command under gdb, ti understand where it got crashed.
```
(gdb) bt
```

**Comment by smallkid** [comment]
smallkid@darkstar03X-PC:~/sdr/xtrx-sdr/images_2019/sources/build/libxtrx$ gdb --args ./test_xtrx -t -l9
 ....................
(gdb) r
Starting program: /home/smallkid/sdr/xtrx-sdr/images_2019/sources/build/libxtrx/test_xtrx -t -l9
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7ab8700 (LWP 7200)]

Thread 1 "test_xtrx" received signal SIGSEGV, Segmentation fault.
__GI__IO_fputs (str=0x7fffffffa6f0 "13:28:48.894923 DEBUG:  find_usb_match:416 [USB3] usb3380: comparing devices -1/-1/-1 <> 1/3/2\n", fp=0x0) at iofputs.c:36
36	iofputs.c: No such file or directory.
(gdb) bt
#0  __GI__IO_fputs (str=0x7fffffffa6f0 "13:28:48.894923 DEBUG:  find_usb_match:416 [USB3] usb3380: comparing devices -1/-1/-1 <> 1/3/2\n", fp=0x0) at iofputs.c:36
#1  0x00007ffff7d229b9 in s_def_logging (l=5, stm=0x7ffff7ab96b8, nsec=894923688, sybsystem=0x7ffff7d31172 "USB3", function=0x7ffff7d31a10 <__FUNCTION__.6557> "find_usb_match", 
    file=0x7ffff7d31118 "/home/smallkid/sdr/xtrx-sdr/images_2019/sources/libxtrxll/mod_usb3380/xtrxll_libusb3380.c", lineno=416, fmt=0x7ffff7d31268 "usb3380: comparing devices %d/%d/%d <> %d/%d/%d\n", 
    list=0x7fffffffabe0) at /home/smallkid/sdr/xtrx-sdr/images_2019/sources/libxtrxll/xtrxll_log.c:112
#2  0x00007ffff7d22b96 in xtrxll_vlog (l=XTRXLL_DEBUG, sybsystem=0x7ffff7d31172 "USB3", function=0x7ffff7d31a10 <__FUNCTION__.6557> "find_usb_match", 
    file=0x7ffff7d31118 "/home/smallkid/sdr/xtrx-sdr/images_2019/sources/libxtrxll/mod_usb3380/xtrxll_libusb3380.c", line=416, fmt=0x7ffff7d31268 "usb3380: comparing devices %d/%d/%d <> %d/%d/%d\n", 
    list=0x7fffffffabe0) at /home/smallkid/sdr/xtrx-sdr/images_2019/sources/libxtrxll/xtrxll_log.c:152
#3  0x00007ffff7d22ada in xtrxll_log (l=XTRXLL_DEBUG, sybsystem=0x7ffff7d31172 "USB3", function=0x7ffff7d31a10 <__FUNCTION__.6557> "find_usb_match", 
    file=0x7ffff7d31118 "/home/smallkid/sdr/xtrx-sdr/images_2019/sources/libxtrxll/mod_usb3380/xtrxll_libusb3380.c", line=416, fmt=0x7ffff7d31268 "usb3380: comparing devices %d/%d/%d <> %d/%d/%d\n")
    at /home/smallkid/sdr/xtrx-sdr/images_2019/sources/libxtrxll/xtrxll_log.c:134
#4  0x00007ffff7d2a8ee in find_usb_match (usbdev=0x5555555765c0, devices=7, usb_bus=-1, usb_port=-1, usb_addr=-1, devid=0x7fffffffad94, devid_s=0x7fffffffaea0 "1/3/2", devid_s_sz=16)
    at /home/smallkid/sdr/xtrx-sdr/images_2019/sources/libxtrxll/mod_usb3380/xtrxll_libusb3380.c:414
#5  0x00007ffff7d2abd3 in xtrxllusb3380v0_open (device=0x0, flags=0, pdev=0x7fffffffaf10) at /home/smallkid/sdr/xtrx-sdr/images_2019/sources/libxtrxll/mod_usb3380/xtrxll_libusb3380.c:473
#6  0x00007ffff7d2952f in xtrxll_open (device=0x0, flags=0, odev=0x7fffffffaf30) at /home/smallkid/sdr/xtrx-sdr/images_2019/sources/libxtrxll/xtrxll_api.c:233
#7  0x00007ffff7f7bcbb in xtrx_open (device=0x0, flags=265, outdev=0x7fffffffb098) at /home/smallkid/sdr/xtrx-sdr/images_2019/sources/libxtrx/xtrx.c:314
#8  0x0000555555556ea9 in main (argc=<optimized out>, argv=<optimized out>) at /home/smallkid/sdr/xtrx-sdr/images_2019/sources/libxtrx/test_xtrx.c:808
(gdb)
